export const SMART_GUIDES_THRESHOLD_PX = 6;
export const SMART_GUIDES_RELEASE_PX = 10;
export const SMART_GUIDES_MAX_DISTANCE_PX = 280;
export const SMART_GUIDES_MIN_LINE_LENGTH_PX = 84;
export const SMART_GUIDES_MAX_LINE_LENGTH_PX = 260;
export const SMART_GUIDES_CANDIDATE_BUFFER_PX = 320;
